### ISSUE TITLE
Your run length decoder decodes improperly 

### ISSUE THREAD

**Issue by AbleTheAbove** [Bernardozomer/rle-rs#1]
![image](https://user-images.githubusercontent.com/75036841/149745694-54497e7c-5846-41ac-9eb2-090809355755.png)

as you can see in the above the original is way less than the decoded

**Comment by Bernardozomer** [comment]
Could you provide me with the original text (or one that is also improperly decoded)?

**Comment by AbleTheAbove** [comment]
I made a mistake with my allocator and it improperly allocated the page I encode into

**Comment by Bernardozomer** [comment]
Can confirm. I'll look into it.

**Comment by Bernardozomer** [comment]
I was getting ready to fix this today when I realized I could no longer reproduce the error. Not sure what was going on.

**Comment by AbleTheAbove** [comment]
As far as I can tell the issue was my fault 🤦‍♂️ not yours 
I just jumped to conclusions! Sorry about the confusion

**Comment by Bernardozomer** [comment]
Don't worry, no problem!
